// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$$0 from "./loaders/Layouts/ProductCard.tsx";
import * as $$$$$$0 from "./sections/Footer/Footer.tsx";
import * as $$$$$$1 from "./sections/Category/CategoryList.tsx";
import * as $$$$$$2 from "./sections/Category/CategoryBanner.tsx";
import * as $$$$$$3 from "./sections/Header/Header.tsx";
import * as $$$$$$4 from "./sections/Theme/Theme.tsx";
import * as $$$$$$5 from "./sections/Newsletter/Newsletter.tsx";
import * as $$$$$$6 from "./sections/Links/Shortcuts.tsx";
import * as $$$$$$7 from "./sections/Links/LinkTree.tsx";
import * as $$$$$$8 from "./sections/Social/InstagramPosts.tsx";
import * as $$$$$$9 from "./sections/Social/WhatsApp.tsx";
import * as $$$$$$10 from "./sections/Images/Carousel.tsx";
import * as $$$$$$11 from "./sections/Images/ImageGallery.tsx";
import * as $$$$$$12 from "./sections/Images/ShoppableBanner.tsx";
import * as $$$$$$13 from "./sections/Images/BannerGrid.tsx";
import * as $$$$$$14 from "./sections/Product/ProductShelf.tsx";
import * as $$$$$$15 from "./sections/Product/ProductDetails.tsx";
import * as $$$$$$16 from "./sections/Product/Wishlist.tsx";
import * as $$$$$$17 from "./sections/Product/SearchResult.tsx";
import * as $$$$$$18 from "./sections/Content/Benefits.tsx";
import * as $$$$$$19 from "./sections/Content/Logos.tsx";
import * as $$$$$$20 from "./sections/Content/Testimonials.tsx";
import * as $$$$$$21 from "./sections/Content/Faq.tsx";
import * as $$$$$$22 from "./sections/Miscellaneous/CampaignTimer.tsx";
import * as $$$$$$23 from "./sections/Miscellaneous/CookieConsent.tsx";
import * as $$$$$$$$$$$0 from "./apps/site.ts";
import * as $$$$$$$$$$$1 from "./apps/decohub.ts";
import * as $$$$$$$$$$$2 from "./apps/custom/utils/transform.ts";
import * as $$$$$$$$$$$3 from "./apps/custom/utils/cart.ts";
import * as $$$$$$$$$$$4 from "./apps/custom/utils/constants.ts";
import * as $$$$$$$$$$$5 from "./apps/custom/utils/openapi/vnda.openapi.gen.ts";
import * as $$$$$$$$$$$6 from "./apps/custom/utils/client/client.ts";
import * as $$$$$$$$$$$7 from "./apps/custom/utils/client/types.ts";
import * as $$$$$$$$$$$8 from "./apps/custom/hooks/context.ts";
import * as $$$$$$$$$$$9 from "./apps/custom/hooks/useCart.ts";
import * as $$$$$$$$$$$10 from "./apps/custom/loaders/productListingPage.ts";
import * as $$$$$$$$$$$11 from "./apps/custom/loaders/productList.ts";
import * as $$$$$$$$$$$12 from "./apps/custom/loaders/cart.ts";
import * as $$$$$$$$$$$13 from "./apps/custom/loaders/proxy.ts";
import * as $$$$$$$$$$$14 from "./apps/custom/loaders/productDetailsPage.ts";
import * as $$$$$$$$$$$15 from "./apps/custom/actions/cart/simulation.ts";
import * as $$$$$$$$$$$16 from "./apps/custom/actions/cart/updateItem.ts";
import * as $$$$$$$$$$$17 from "./apps/custom/actions/cart/updateCart.ts";
import * as $$$$$$$$$$$18 from "./apps/custom/actions/cart/addItem.ts";
import * as $$$$$$$$$$$19 from "./apps/custom/manifest.gen.ts";
import * as $$$$$$$$$$$20 from "./apps/custom/runtime.ts";
import * as $$$$$$$$$$$21 from "./apps/custom/mod.ts";

const manifest = {
  "loaders": {
    "deco-sites/madeiramadeira/loaders/Layouts/ProductCard.tsx": $$$0,
  },
  "sections": {
    "deco-sites/madeiramadeira/sections/Category/CategoryBanner.tsx": $$$$$$2,
    "deco-sites/madeiramadeira/sections/Category/CategoryList.tsx": $$$$$$1,
    "deco-sites/madeiramadeira/sections/Content/Benefits.tsx": $$$$$$18,
    "deco-sites/madeiramadeira/sections/Content/Faq.tsx": $$$$$$21,
    "deco-sites/madeiramadeira/sections/Content/Logos.tsx": $$$$$$19,
    "deco-sites/madeiramadeira/sections/Content/Testimonials.tsx": $$$$$$20,
    "deco-sites/madeiramadeira/sections/Footer/Footer.tsx": $$$$$$0,
    "deco-sites/madeiramadeira/sections/Header/Header.tsx": $$$$$$3,
    "deco-sites/madeiramadeira/sections/Images/BannerGrid.tsx": $$$$$$13,
    "deco-sites/madeiramadeira/sections/Images/Carousel.tsx": $$$$$$10,
    "deco-sites/madeiramadeira/sections/Images/ImageGallery.tsx": $$$$$$11,
    "deco-sites/madeiramadeira/sections/Images/ShoppableBanner.tsx": $$$$$$12,
    "deco-sites/madeiramadeira/sections/Links/LinkTree.tsx": $$$$$$7,
    "deco-sites/madeiramadeira/sections/Links/Shortcuts.tsx": $$$$$$6,
    "deco-sites/madeiramadeira/sections/Miscellaneous/CampaignTimer.tsx":
      $$$$$$22,
    "deco-sites/madeiramadeira/sections/Miscellaneous/CookieConsent.tsx":
      $$$$$$23,
    "deco-sites/madeiramadeira/sections/Newsletter/Newsletter.tsx": $$$$$$5,
    "deco-sites/madeiramadeira/sections/Product/ProductDetails.tsx": $$$$$$15,
    "deco-sites/madeiramadeira/sections/Product/ProductShelf.tsx": $$$$$$14,
    "deco-sites/madeiramadeira/sections/Product/SearchResult.tsx": $$$$$$17,
    "deco-sites/madeiramadeira/sections/Product/Wishlist.tsx": $$$$$$16,
    "deco-sites/madeiramadeira/sections/Social/InstagramPosts.tsx": $$$$$$8,
    "deco-sites/madeiramadeira/sections/Social/WhatsApp.tsx": $$$$$$9,
    "deco-sites/madeiramadeira/sections/Theme/Theme.tsx": $$$$$$4,
  },
  "apps": {
    "deco-sites/madeiramadeira/apps/custom/actions/cart/addItem.ts":
      $$$$$$$$$$$18,
    "deco-sites/madeiramadeira/apps/custom/actions/cart/simulation.ts":
      $$$$$$$$$$$15,
    "deco-sites/madeiramadeira/apps/custom/actions/cart/updateCart.ts":
      $$$$$$$$$$$17,
    "deco-sites/madeiramadeira/apps/custom/actions/cart/updateItem.ts":
      $$$$$$$$$$$16,
    "deco-sites/madeiramadeira/apps/custom/hooks/context.ts": $$$$$$$$$$$8,
    "deco-sites/madeiramadeira/apps/custom/hooks/useCart.ts": $$$$$$$$$$$9,
    "deco-sites/madeiramadeira/apps/custom/loaders/cart.ts": $$$$$$$$$$$12,
    "deco-sites/madeiramadeira/apps/custom/loaders/productDetailsPage.ts":
      $$$$$$$$$$$14,
    "deco-sites/madeiramadeira/apps/custom/loaders/productList.ts":
      $$$$$$$$$$$11,
    "deco-sites/madeiramadeira/apps/custom/loaders/productListingPage.ts":
      $$$$$$$$$$$10,
    "deco-sites/madeiramadeira/apps/custom/loaders/proxy.ts": $$$$$$$$$$$13,
    "deco-sites/madeiramadeira/apps/custom/manifest.gen.ts": $$$$$$$$$$$19,
    "deco-sites/madeiramadeira/apps/custom/mod.ts": $$$$$$$$$$$21,
    "deco-sites/madeiramadeira/apps/custom/runtime.ts": $$$$$$$$$$$20,
    "deco-sites/madeiramadeira/apps/custom/utils/cart.ts": $$$$$$$$$$$3,
    "deco-sites/madeiramadeira/apps/custom/utils/client/client.ts":
      $$$$$$$$$$$6,
    "deco-sites/madeiramadeira/apps/custom/utils/client/types.ts": $$$$$$$$$$$7,
    "deco-sites/madeiramadeira/apps/custom/utils/constants.ts": $$$$$$$$$$$4,
    "deco-sites/madeiramadeira/apps/custom/utils/openapi/vnda.openapi.gen.ts":
      $$$$$$$$$$$5,
    "deco-sites/madeiramadeira/apps/custom/utils/transform.ts": $$$$$$$$$$$2,
    "deco-sites/madeiramadeira/apps/decohub.ts": $$$$$$$$$$$1,
    "deco-sites/madeiramadeira/apps/site.ts": $$$$$$$$$$$0,
  },
  "name": "deco-sites/madeiramadeira",
  "baseUrl": import.meta.url,
};

export type Manifest = typeof manifest;

export default manifest;
